/*
    Jail Programming Language Copyright (C) 2022 SolindekDev
        - Code generated by Jail Programming Language
*/

use std::io;
use std::process;

#[warn(unused_variables)]
#[warn(unused_mut)]
#[warn(unused_imports)]
#[warn(unused_features)]
#[warn(dead_code)]
#[warn(non_snake_case)]
#[warn(non_upper_case_globals)]
#[warn(unreachable_code)]
#[warn(while_true)]
#[warn(unused_unsafe)]

type int     = i32;
type uint    = i8;
type float   = f64;
type ufloat  = f32;

fn main() {
	let calculations_232128: float = (1+1) as float;
	let calculations_1954952: float = (1+2*3/4) as float;
	let calculations_1099688: float = (9+221) as float;
}