[package]
name = "jail_ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jail_token = {path = "../jail_token"}
ansi_term = "0.12"